[adme]
gnn_atom_enabled = true
gnn_comp_enabled = false
gnn_spacial_enabled = false
mlp_enabled = true

# Increasing layers may or may not improve model performance. It will slow down inference and training.
# We have it lower than idea now to improve speed.


gnn_atom_layers = 1
gnn_comp_layers = 2
# It seems a higher value here, to a point, is relatively cheap, and produces better results. High values increase
# memory use; have crashed with out-of-memory with this at 7.
gnn_spacial_layers = 2
#gnn_spacial_layers = 7
# It seems a higher value here, to a point, is relatively cheap, and produces better results.
mlp_layers = 5

# todo: Eval where this should live. Currently hard-coded.
## Note: Excluding H or not appears not to make any notable difference at first;
## Experiment with this more later.
#exclude_hydrogen = true