//! Versioned, integrity-checked train/validation/test split manifests.
//!
//! Manifests are generated by `scripts/train_test_split.py` from an exact CSV
//! snapshot. They live at
//! `<dataset directory>/split_manifests/<dataset>.split.json`. Training refuses
//! to continue if the CSV hash changed, a row is missing, or a molecule/scaffold
//! occurs in more than one split.

use std::{
    collections::{BTreeMap, HashMap},
    fmt, fs, io,
    path::{Path, PathBuf},
};

use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::therapeutic::DatasetTdc;

const MANIFEST_SCHEMA_VERSION: u32 = 1;
const SPLIT_ALGORITHM: &str = "deterministic_scaffold_group";
const SPLIT_ALGORITHM_VERSION: u32 = 1;

/// Indices into the exact source CSV snapshot, after its manifest has passed
/// all integrity and leakage checks.
#[derive(Clone, Debug)]
pub(in crate::therapeutic) struct TrainTestSplit {
    pub dataset: DatasetTdc,
    pub train: Vec<usize>,
    pub validation: Vec<usize>,
    pub test: Vec<usize>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct SplitManifest {
    schema_version: u32,
    dataset: ManifestDataset,
    split: ManifestSplit,
    expected: ExpectedProperties,
    rows: BTreeMap<String, RowAssignment>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct ManifestDataset {
    name: String,
    version: String,
    source_file: String,
    source_file_sha256: String,
    row_count: usize,
    smiles_column: String,
    target_column: String,
    rdkit_version: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    structure_overrides_sha256: Option<String>,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct ManifestSplit {
    algorithm: String,
    algorithm_version: u32,
    seed: u64,
    fractions: SplitFractions,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct SplitFractions {
    train: f64,
    validation: f64,
    test: f64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct ExpectedProperties {
    split_counts: SplitCounts,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    class_distribution: Option<BTreeMap<String, BTreeMap<String, usize>>>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    target_summary: Option<BTreeMap<String, TargetSummary>>,
}

#[derive(Clone, Debug, Deserialize, Serialize, PartialEq, Eq)]
struct SplitCounts {
    train: usize,
    validation: usize,
    test: usize,
}

impl SplitCounts {
    fn get(&self, split: SplitName) -> usize {
        match split {
            SplitName::Train => self.train,
            SplitName::Validation => self.validation,
            SplitName::Test => self.test,
        }
    }

    fn increment(&mut self, split: SplitName) {
        match split {
            SplitName::Train => self.train += 1,
            SplitName::Validation => self.validation += 1,
            SplitName::Test => self.test += 1,
        }
    }

    fn total(&self) -> usize {
        self.train + self.validation + self.test
    }
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct TargetSummary {
    count: usize,
    min: f64,
    max: f64,
    mean: f64,
}

#[derive(Clone, Debug, Deserialize, Serialize)]
struct RowAssignment {
    parent_inchi_key: String,
    scaffold_key: String,
    split: SplitName,
}

#[derive(Clone, Copy, Debug, Deserialize, Serialize, PartialEq, Eq, Hash)]
#[serde(rename_all = "lowercase")]
enum SplitName {
    Train,
    Validation,
    Test,
}

impl SplitName {
    const ALL: [Self; 3] = [Self::Train, Self::Validation, Self::Test];

    fn as_str(self) -> &'static str {
        match self {
            Self::Train => "train",
            Self::Validation => "validation",
            Self::Test => "test",
        }
    }
}

impl fmt::Display for SplitName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.as_str())
    }
}

impl TrainTestSplit {
    /// Load and fully validate the manifest associated with `csv_path`.
    pub fn load(dataset: DatasetTdc, csv_path: &Path, tgt_col: usize) -> io::Result<Self> {
        let manifest_path = manifest_path(csv_path)?;
        let manifest_bytes = fs::read(&manifest_path).map_err(|e| {
            io::Error::new(
                e.kind(),
                format!(
                    "Unable to read split manifest {manifest_path:?}: {e}. Generate it with: \
                     python scripts/train_test_split.py --data-dir {:?} --dataset-version <version>",
                    csv_path.parent().unwrap_or_else(|| Path::new("."))
                ),
            )
        })?;
        let manifest: SplitManifest = serde_json::from_slice(&manifest_bytes).map_err(|e| {
            invalid_data(format!(
                "Invalid split manifest JSON at {manifest_path:?}: {e}"
            ))
        })?;
        let csv_bytes = fs::read(csv_path)?;

        validate_manifest(dataset, csv_path, tgt_col, &csv_bytes, &manifest)?;

        let mut result = Self {
            dataset,
            train: Vec::with_capacity(manifest.expected.split_counts.train),
            validation: Vec::with_capacity(manifest.expected.split_counts.validation),
            test: Vec::with_capacity(manifest.expected.split_counts.test),
        };

        // Numeric iteration avoids JSON object-key lexicographic ordering ("10" before "2").
        for row_id in 0..manifest.dataset.row_count {
            let assignment = &manifest.rows[&row_id.to_string()];
            match assignment.split {
                SplitName::Train => result.train.push(row_id),
                SplitName::Validation => result.validation.push(row_id),
                SplitName::Test => result.test.push(row_id),
            }
        }

        Ok(result)
    }
}

fn manifest_path(csv_path: &Path) -> io::Result<PathBuf> {
    let parent = csv_path.parent().unwrap_or_else(|| Path::new("."));
    let stem = csv_path
        .file_stem()
        .and_then(|s| s.to_str())
        .ok_or_else(|| invalid_data(format!("Invalid dataset CSV filename: {csv_path:?}")))?;
    Ok(parent
        .join("split_manifests")
        .join(format!("{stem}.split.json")))
}

fn validate_manifest(
    dataset: DatasetTdc,
    csv_path: &Path,
    tgt_col: usize,
    csv_bytes: &[u8],
    manifest: &SplitManifest,
) -> io::Result<()> {
    if manifest.schema_version != MANIFEST_SCHEMA_VERSION {
        return Err(invalid_data(format!(
            "Unsupported split manifest schema version {} (expected {MANIFEST_SCHEMA_VERSION})",
            manifest.schema_version
        )));
    }
    if manifest.dataset.name != dataset.name() {
        return Err(invalid_data(format!(
            "Split manifest dataset is {:?}, but training requested {:?}",
            manifest.dataset.name,
            dataset.name()
        )));
    }
    if manifest.dataset.version.trim().is_empty() {
        return Err(invalid_data("Split manifest has no dataset version"));
    }
    if manifest.dataset.rdkit_version.trim().is_empty() {
        return Err(invalid_data("Split manifest has no RDKit version"));
    }
    if let Some(hash) = &manifest.dataset.structure_overrides_sha256
        && !is_sha256_hex(hash)
    {
        return Err(invalid_data(
            "Split manifest has an invalid structure-override SHA-256",
        ));
    }
    if manifest.split.algorithm != SPLIT_ALGORITHM
        || manifest.split.algorithm_version != SPLIT_ALGORITHM_VERSION
    {
        return Err(invalid_data(format!(
            "Unsupported split algorithm {} v{} (expected {SPLIT_ALGORITHM} v{SPLIT_ALGORITHM_VERSION})",
            manifest.split.algorithm, manifest.split.algorithm_version
        )));
    }
    if manifest.split.seed == 0 {
        return Err(invalid_data("Split seed must be explicit and non-zero"));
    }

    let fraction_sum = manifest.split.fractions.train
        + manifest.split.fractions.validation
        + manifest.split.fractions.test;
    if (fraction_sum - 1.0).abs() > 1e-9
        || manifest.split.fractions.train <= 0.0
        || manifest.split.fractions.validation <= 0.0
        || manifest.split.fractions.test <= 0.0
    {
        return Err(invalid_data(format!(
            "Invalid split fractions: train={}, validation={}, test={}",
            manifest.split.fractions.train,
            manifest.split.fractions.validation,
            manifest.split.fractions.test
        )));
    }

    let source_file = csv_path
        .file_name()
        .and_then(|s| s.to_str())
        .ok_or_else(|| invalid_data(format!("Invalid dataset CSV filename: {csv_path:?}")))?;
    if manifest.dataset.source_file != source_file {
        return Err(invalid_data(format!(
            "Manifest source file {:?} does not match CSV {:?}",
            manifest.dataset.source_file, source_file
        )));
    }

    let actual_hash = sha256_hex(csv_bytes);
    if !is_sha256_hex(&manifest.dataset.source_file_sha256)
        || !manifest
            .dataset
            .source_file_sha256
            .eq_ignore_ascii_case(&actual_hash)
    {
        return Err(invalid_data(format!(
            "Dataset snapshot hash mismatch for {csv_path:?}: manifest={}, actual={actual_hash}. \
             Regenerate the manifest only if this CSV is an intentional new dataset version.",
            manifest.dataset.source_file_sha256
        )));
    }

    if manifest.rows.len() != manifest.dataset.row_count {
        return Err(invalid_data(format!(
            "Manifest row map contains {} rows, expected {}",
            manifest.rows.len(),
            manifest.dataset.row_count
        )));
    }
    if manifest.expected.split_counts.total() != manifest.dataset.row_count {
        return Err(invalid_data(format!(
            "Expected split counts total {}, but dataset row count is {}",
            manifest.expected.split_counts.total(),
            manifest.dataset.row_count
        )));
    }
    for split in SplitName::ALL {
        if manifest.expected.split_counts.get(split) == 0 {
            return Err(invalid_data(format!("The {split} split is empty")));
        }
    }
    if manifest.expected.class_distribution.is_some() == manifest.expected.target_summary.is_some()
    {
        return Err(invalid_data(
            "Manifest must contain exactly one of class_distribution or target_summary",
        ));
    }

    let mut actual_counts = SplitCounts {
        train: 0,
        validation: 0,
        test: 0,
    };
    let mut parent_splits: HashMap<&str, SplitName> = HashMap::new();
    let mut scaffold_splits: HashMap<&str, SplitName> = HashMap::new();
    for row_id in 0..manifest.dataset.row_count {
        let row_key = row_id.to_string();
        let assignment = manifest.rows.get(&row_key).ok_or_else(|| {
            invalid_data(format!(
                "Source row {row_id} is absent from the split manifest"
            ))
        })?;
        if !is_standard_inchi_key(&assignment.parent_inchi_key) {
            return Err(invalid_data(format!(
                "Source row {row_id} has invalid standardized parent InChIKey {:?}",
                assignment.parent_inchi_key
            )));
        }
        if assignment.scaffold_key.trim().is_empty() {
            return Err(invalid_data(format!(
                "Source row {row_id} has an empty scaffold group"
            )));
        }
        reject_cross_split_key(
            "standardized parent molecule",
            &assignment.parent_inchi_key,
            assignment.split,
            &mut parent_splits,
        )?;
        reject_cross_split_key(
            "scaffold",
            &assignment.scaffold_key,
            assignment.split,
            &mut scaffold_splits,
        )?;
        actual_counts.increment(assignment.split);
    }

    // Reject non-canonical or out-of-range object keys as well as missing numeric keys.
    for key in manifest.rows.keys() {
        let parsed = key
            .parse::<usize>()
            .map_err(|_| invalid_data(format!("Invalid source row ID key {key:?}")))?;
        if key != &parsed.to_string() || parsed >= manifest.dataset.row_count {
            return Err(invalid_data(format!(
                "Non-canonical or out-of-range source row ID key {key:?}"
            )));
        }
    }
    if actual_counts != manifest.expected.split_counts {
        return Err(invalid_data(format!(
            "Manifest split counts are {:?}, expected {:?}",
            actual_counts, manifest.expected.split_counts
        )));
    }

    validate_csv_and_targets(csv_bytes, tgt_col, manifest)?;
    Ok(())
}

fn validate_csv_and_targets(
    csv_bytes: &[u8],
    tgt_col: usize,
    manifest: &SplitManifest,
) -> io::Result<()> {
    let mut reader = csv::Reader::from_reader(csv_bytes);
    let headers = reader.headers()?.clone();
    let smiles_col = headers
        .iter()
        .position(|h| h == manifest.dataset.smiles_column)
        .ok_or_else(|| {
            invalid_data(format!(
                "CSV has no manifest SMILES column {:?}",
                manifest.dataset.smiles_column
            ))
        })?;
    let target_col = headers
        .iter()
        .position(|h| h == manifest.dataset.target_column)
        .ok_or_else(|| {
            invalid_data(format!(
                "CSV has no manifest target column {:?}",
                manifest.dataset.target_column
            ))
        })?;
    if smiles_col == target_col {
        return Err(invalid_data("SMILES and target columns are the same"));
    }
    if target_col != tgt_col {
        return Err(invalid_data(format!(
            "Training target column index is {tgt_col}, but the verified manifest target {:?} is at index {target_col}",
            manifest.dataset.target_column
        )));
    }

    let mut csv_row_count = 0usize;
    let mut actual_distribution: BTreeMap<String, BTreeMap<String, usize>> = BTreeMap::new();
    let mut target_values: BTreeMap<String, Vec<f64>> = BTreeMap::new();
    for result in reader.records() {
        let record = result?;
        let row_id = csv_row_count;
        csv_row_count += 1;
        let target_raw = record
            .get(target_col)
            .ok_or_else(|| invalid_data(format!("Source row {row_id} has no target column")))?;
        let target = target_raw.trim().parse::<f64>().map_err(|e| {
            invalid_data(format!(
                "Source row {row_id} has non-numeric target {target_raw:?}: {e}"
            ))
        })?;
        if !target.is_finite() {
            return Err(invalid_data(format!(
                "Source row {row_id} has non-finite target {target_raw:?}"
            )));
        }
        let split = manifest.rows[&row_id.to_string()]
            .split
            .as_str()
            .to_string();
        target_values.entry(split.clone()).or_default().push(target);

        if manifest.expected.class_distribution.is_some() {
            let class = binary_class(target).ok_or_else(|| {
                invalid_data(format!(
                    "Classification manifest has non-binary target {target} at source row {row_id}"
                ))
            })?;
            *actual_distribution
                .entry(split)
                .or_default()
                .entry(class.to_string())
                .or_default() += 1;
        }
    }
    if csv_row_count != manifest.dataset.row_count {
        return Err(invalid_data(format!(
            "CSV contains {csv_row_count} records, but its manifest covers {}",
            manifest.dataset.row_count
        )));
    }

    if let Some(expected) = &manifest.expected.class_distribution {
        ensure_all_split_keys(&mut actual_distribution);
        if &actual_distribution != expected {
            return Err(invalid_data(format!(
                "Class distribution mismatch: actual={actual_distribution:?}, expected={expected:?}"
            )));
        }
    }
    if let Some(expected) = &manifest.expected.target_summary {
        for split in SplitName::ALL {
            let name = split.as_str();
            let values = target_values
                .get(name)
                .ok_or_else(|| invalid_data(format!("No target values found for {name} split")))?;
            let actual = summarize_targets(values);
            let wanted = expected.get(name).ok_or_else(|| {
                invalid_data(format!("Manifest has no target summary for {name} split"))
            })?;
            if actual.count != wanted.count
                || !approximately_equal(actual.min, wanted.min)
                || !approximately_equal(actual.max, wanted.max)
                || !approximately_equal(actual.mean, wanted.mean)
            {
                return Err(invalid_data(format!(
                    "Target summary mismatch for {name}: actual={actual:?}, expected={wanted:?}"
                )));
            }
        }
    }

    Ok(())
}

fn ensure_all_split_keys(distribution: &mut BTreeMap<String, BTreeMap<String, usize>>) {
    for split in SplitName::ALL {
        distribution.entry(split.as_str().to_string()).or_default();
    }
}

fn summarize_targets(values: &[f64]) -> TargetSummary {
    let min = values.iter().copied().fold(f64::INFINITY, f64::min);
    let max = values.iter().copied().fold(f64::NEG_INFINITY, f64::max);
    let mean = values.iter().sum::<f64>() / values.len() as f64;
    TargetSummary {
        count: values.len(),
        min,
        max,
        mean,
    }
}

fn reject_cross_split_key<'a>(
    kind: &str,
    key: &'a str,
    split: SplitName,
    seen: &mut HashMap<&'a str, SplitName>,
) -> io::Result<()> {
    if let Some(previous) = seen.insert(key, split)
        && previous != split
    {
        return Err(invalid_data(format!(
            "{kind} {key:?} leaks across {previous} and {split} splits"
        )));
    }
    Ok(())
}

fn binary_class(value: f64) -> Option<u8> {
    if value.abs() <= 1e-12 {
        Some(0)
    } else if (value - 1.0).abs() <= 1e-12 {
        Some(1)
    } else {
        None
    }
}

fn approximately_equal(a: f64, b: f64) -> bool {
    (a - b).abs() <= 1e-10 * (1.0 + a.abs().max(b.abs()))
}

fn is_standard_inchi_key(value: &str) -> bool {
    let bytes = value.as_bytes();
    bytes.len() == 27
        && bytes[14] == b'-'
        && bytes[25] == b'-'
        && bytes
            .iter()
            .enumerate()
            .all(|(i, b)| i == 14 || i == 25 || b.is_ascii_uppercase())
}

fn is_sha256_hex(value: &str) -> bool {
    value.len() == 64 && value.bytes().all(|b| b.is_ascii_hexdigit())
}

fn sha256_hex(bytes: &[u8]) -> String {
    format!("{:x}", Sha256::digest(bytes))
}

fn invalid_data(message: impl Into<String>) -> io::Error {
    io::Error::new(io::ErrorKind::InvalidData, message.into())
}

#[cfg(test)]
mod tests {
    use std::{
        sync::atomic::{AtomicU64, Ordering},
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::*;

    static NEXT_ID: AtomicU64 = AtomicU64::new(0);

    struct FixtureDir(PathBuf);

    impl FixtureDir {
        fn new() -> Self {
            let nonce = SystemTime::now()
                .duration_since(UNIX_EPOCH)
                .unwrap()
                .as_nanos();
            let path = std::env::temp_dir().join(format!(
                "molchanica-split-manifest-{}-{nonce}-{}",
                std::process::id(),
                NEXT_ID.fetch_add(1, Ordering::Relaxed)
            ));
            fs::create_dir_all(path.join("split_manifests")).unwrap();
            Self(path)
        }
    }

    impl Drop for FixtureDir {
        fn drop(&mut self) {
            let _ = fs::remove_dir_all(&self.0);
        }
    }

    fn valid_fixture() -> (FixtureDir, PathBuf, SplitManifest) {
        let dir = FixtureDir::new();
        let csv_path = dir.0.join("caco2_wang.csv");
        let csv =
            b"Drug_ID,Drug,Y\na,CC,0\nb,CCC,1\nc,CCCC,0\nd,CCCCC,1\ne,CCCCCC,0\nf,CCCCCCC,1\n";
        fs::write(&csv_path, csv).unwrap();

        let assignments = [
            ("AAAAAAAAAAAAAA-BBBBBBBBBB-C", "ACYCLIC:0", SplitName::Train),
            ("CCCCCCCCCCCCCC-DDDDDDDDDD-E", "ACYCLIC:1", SplitName::Train),
            (
                "FFFFFFFFFFFFFF-GGGGGGGGGG-H",
                "ACYCLIC:2",
                SplitName::Validation,
            ),
            (
                "IIIIIIIIIIIIII-JJJJJJJJJJ-K",
                "ACYCLIC:3",
                SplitName::Validation,
            ),
            ("LLLLLLLLLLLLLL-MMMMMMMMMM-N", "ACYCLIC:4", SplitName::Test),
            ("OOOOOOOOOOOOOO-PPPPPPPPPP-Q", "ACYCLIC:5", SplitName::Test),
        ];
        let rows = assignments
            .into_iter()
            .enumerate()
            .map(|(row_id, (parent_inchi_key, scaffold_key, split))| {
                (
                    row_id.to_string(),
                    RowAssignment {
                        parent_inchi_key: parent_inchi_key.to_string(),
                        scaffold_key: scaffold_key.to_string(),
                        split,
                    },
                )
            })
            .collect();
        let per_split = BTreeMap::from([
            (
                "train".to_string(),
                BTreeMap::from([("0".to_string(), 1), ("1".to_string(), 1)]),
            ),
            (
                "validation".to_string(),
                BTreeMap::from([("0".to_string(), 1), ("1".to_string(), 1)]),
            ),
            (
                "test".to_string(),
                BTreeMap::from([("0".to_string(), 1), ("1".to_string(), 1)]),
            ),
        ]);
        let manifest = SplitManifest {
            schema_version: MANIFEST_SCHEMA_VERSION,
            dataset: ManifestDataset {
                name: "caco2_wang".to_string(),
                version: "fixture-v1".to_string(),
                source_file: "caco2_wang.csv".to_string(),
                source_file_sha256: sha256_hex(csv),
                row_count: 6,
                smiles_column: "Drug".to_string(),
                target_column: "Y".to_string(),
                rdkit_version: "fixture".to_string(),
                structure_overrides_sha256: None,
            },
            split: ManifestSplit {
                algorithm: SPLIT_ALGORITHM.to_string(),
                algorithm_version: SPLIT_ALGORITHM_VERSION,
                seed: 42,
                fractions: SplitFractions {
                    train: 0.7,
                    validation: 0.1,
                    test: 0.2,
                },
            },
            expected: ExpectedProperties {
                split_counts: SplitCounts {
                    train: 2,
                    validation: 2,
                    test: 2,
                },
                class_distribution: Some(per_split),
                target_summary: None,
            },
            rows,
        };
        (dir, csv_path, manifest)
    }

    fn write_manifest(dir: &FixtureDir, manifest: &SplitManifest) {
        let path = dir.0.join("split_manifests/caco2_wang.split.json");
        fs::write(path, serde_json::to_vec_pretty(manifest).unwrap()).unwrap();
    }

    #[test]
    fn loads_complete_non_leaking_manifest() {
        let (dir, csv_path, manifest) = valid_fixture();
        write_manifest(&dir, &manifest);
        let split = TrainTestSplit::load(DatasetTdc::Caco2Wang, &csv_path, 2).unwrap();
        assert_eq!(split.train, vec![0, 1]);
        assert_eq!(split.validation, vec![2, 3]);
        assert_eq!(split.test, vec![4, 5]);
    }

    #[test]
    fn rejects_parent_molecule_leakage() {
        let (dir, csv_path, mut manifest) = valid_fixture();
        manifest.rows.get_mut("2").unwrap().parent_inchi_key =
            manifest.rows["0"].parent_inchi_key.clone();
        write_manifest(&dir, &manifest);
        let error = TrainTestSplit::load(DatasetTdc::Caco2Wang, &csv_path, 2).unwrap_err();
        assert!(error.to_string().contains("leaks across"));
    }

    #[test]
    fn rejects_scaffold_leakage() {
        let (dir, csv_path, mut manifest) = valid_fixture();
        manifest.rows.get_mut("2").unwrap().scaffold_key = manifest.rows["0"].scaffold_key.clone();
        write_manifest(&dir, &manifest);
        let error = TrainTestSplit::load(DatasetTdc::Caco2Wang, &csv_path, 2).unwrap_err();
        assert!(error.to_string().contains("scaffold"));
        assert!(error.to_string().contains("leaks across"));
    }

    #[test]
    fn rejects_stale_dataset_snapshot() {
        let (dir, csv_path, manifest) = valid_fixture();
        write_manifest(&dir, &manifest);
        fs::write(&csv_path, b"Drug_ID,Drug,Y\na,CC,1\n").unwrap();
        let error = TrainTestSplit::load(DatasetTdc::Caco2Wang, &csv_path, 2).unwrap_err();
        assert!(error.to_string().contains("hash mismatch"));
    }

    #[test]
    fn rejects_incomplete_row_coverage() {
        let (dir, csv_path, mut manifest) = valid_fixture();
        manifest.rows.remove("5");
        write_manifest(&dir, &manifest);
        let error = TrainTestSplit::load(DatasetTdc::Caco2Wang, &csv_path, 2).unwrap_err();
        assert!(error.to_string().contains("row map contains"));
    }

    #[test]
    #[ignore = "requires TDC_DATA_DIR to point at a complete TDC snapshot"]
    fn loads_every_manifest_from_a_tdc_snapshot() {
        let root = PathBuf::from(
            std::env::var_os("TDC_DATA_DIR")
                .expect("set TDC_DATA_DIR to the directory containing the TDC CSV files"),
        );

        for dataset in DatasetTdc::all() {
            let csv_path = root.join(format!("{}.csv", dataset.name()));
            let mut reader = csv::Reader::from_path(&csv_path).unwrap();
            let headers = reader.headers().unwrap();
            let target_col = headers
                .iter()
                .position(|header| header == "Y" || header == "label")
                .unwrap_or_else(|| panic!("no target column in {}", csv_path.display()));
            let row_count = reader.records().count();

            let split = TrainTestSplit::load(dataset, &csv_path, target_col).unwrap();
            assert_eq!(
                split.train.len() + split.validation.len() + split.test.len(),
                row_count,
                "{}",
                csv_path.display()
            );
        }
    }
}
