//! For playing back MD trajectories: Generated by Molchanica, or from a file created by any
//! MD software.

use std::{
    collections::HashMap,
    io,
    io::ErrorKind,
    path::{Path, PathBuf},
};

use bio_files::gromacs::gro::Gro;
use dynamics::{FfMolType, snapshot::Snapshot};
use graphics::Scene;
use lin_alg::f64::Vec3;

use crate::{
    drawing::{EntityClass, MoleculeView, draw_mol, draw_water},
    mol_manip::ManipMode,
    molecules::{Atom, MolGenericRef, MolType, common::MoleculeCommon, small::MoleculeSmall},
    state::{OperatingMode, State},
    util::handle_err,
};

/// Used to map our molecule system to trajectories; the latter of which generally (always in formats
/// we've encountered and created) uses an array of positions, not corresponding to molecules. Breaking
/// these down into molecules has implications for our rendering system, i.e. neatly and consistently
/// visualizing MD output with the same visuals as our normal viewing system.
#[derive(Clone, Debug)]
pub struct ViewerMolecule {
    pub mol_type: MolType,
    /// Note: If we have multiple "copies" of a molecule, we duplicate here.
    pub mol: MoleculeCommon,
    /// Atom (start, end) index, e.g. of a snapshot/frame.
    pub range: (usize, usize),
}

/// E.g. from a .gro file or similar.
pub struct ViewerMolSet {
    pub path: Option<PathBuf>,
    pub name: String,
    pub mols: Vec<ViewerMolecule>,
    /// Derivative of mols. Used to compare to atom counts in trajectories.
    pub atom_count: usize,
    /// Derived from all molecule ranges in the set
    pub range_covered: (usize, usize),
    /// A range overlap is probably a fault of some sort in the ranges here.
    pub range_overlaps: bool,
}

impl ViewerMolSet {
    /// This constructor computes the derivative values.
    pub fn new(path: Option<PathBuf>, name: String, mols: Vec<ViewerMolecule>) -> Self {
        let atom_count = mols.iter().map(|m| m.mol.atoms.len()).sum();

        let range_covered = if mols.is_empty() {
            (0, 0)
        } else {
            let start = mols.iter().map(|m| m.range.0).min().unwrap();
            let end = mols.iter().map(|m| m.range.1).max().unwrap();
            (start, end)
        };

        let mut sorted_ranges = mols.iter().map(|m| m.range).collect::<Vec<_>>();
        sorted_ranges.sort_by_key(|r| r.0);

        let mut range_overlaps = false;
        for pair in sorted_ranges.windows(2) {
            let a = pair[0];
            let b = pair[1];

            if b.0 < a.1 {
                range_overlaps = true;
                break;
            }
        }

        Self {
            path,
            name,
            mols,
            atom_count,
            range_covered,
            range_overlaps,
        }
    }
}

#[derive(Default)]
pub struct SnapshotViewer {
    // pub struct SnapshotViewer<M: MolGeneric> {
    /// Snapshots currently active and loaded in memory; from an MD run, or loading
    /// a trajectory file.
    pub snapshots: Vec<Snapshot>,
    pub current_snapshot: Option<usize>,
    /// We maintain independent copies of these from the primary state. These are what we display
    /// after an MD run. They may be created as copies of molecules in the primary state, or loaded
    /// from an MD file like .gro.
    pub mol_sets: Vec<ViewerMolSet>,
    pub mol_set_active: Option<usize>,
    // pub mols: Vec<M>, // todo: Evaluate if this makes more sense
    // pub custom_solvents: Vec<MoleculeSmall>,
    pub slider_posit_ui: usize,
}

impl SnapshotViewer {
    pub fn get_active_snap(&self) -> Option<&Snapshot> {
        let Some(i) = self.current_snapshot else {
            return None;
        };

        self.get_snap(i)
    }

    pub fn get_snap(&self, i: usize) -> Option<&Snapshot> {
        if i < self.snapshots.len() {
            Some(&self.snapshots[i])
        } else {
            None
        }
    }

    pub fn get_active_mol_set(&self) -> Option<&ViewerMolSet> {
        let i = self.mol_set_active?;

        if i < self.mol_sets.len() {
            Some(&self.mol_sets[i])
        } else {
            None
        }
    }

    pub fn get_active_mol_set_mut(&mut self) -> Option<&mut ViewerMolSet> {
        let i = self.mol_set_active?;

        if i < self.mol_sets.len() {
            Some(&mut self.mol_sets[i])
        } else {
            None
        }
    }

    /// Update each molecule's atom positions to that in the chosen snapshot.
    pub fn change_snapshot(&mut self, snap_i: usize) -> io::Result<()> {
        let mol_start_indices = {
            let Some(set) = self.get_active_mol_set() else {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    "No active mol set when changing snap.",
                ));
            };

            set.mols.iter().map(|m| m.range.0).collect::<Vec<_>>()
        };

        let posits_by_mol = {
            let Some(snap) = self.get_snap(snap_i) else {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    "Snapshot not found when changing",
                ));
            };

            snap.unflatten(&mol_start_indices)?
        };

        let Some(mols) = self.get_active_mol_set_mut() else {
            return Err(io::Error::new(
                ErrorKind::NotFound,
                "No active mol set when changing snap.",
            ));
        };

        for (i_posits, mol) in mols.mols.iter_mut().enumerate() {
            for (i_p, p) in mol.mol.atom_posits.iter_mut().enumerate() {
                *p = posits_by_mol[i_posits][i_p].0.into();
            }
        }

        Ok(())
    }

    /// Opens a GROMACS gro file. We currently are adding it only for the purposes of MD playback.
    /// This replaces all molecules in the viewer.
    /// todo: Support more generally as a molecule format A/R, and possibly move this if so.
    pub fn load_gro(&mut self, path: &Path) -> io::Result<()> {
        let gro = Gro::load(path)?;

        // Group atoms by mol_name, preserving first-seen order.
        let mut mol_order: Vec<String> = Vec::new();
        let mut mol_atom_groups: HashMap<String, Vec<usize>> = HashMap::new();

        for (i, atom) in gro.atoms.iter().enumerate() {
            if !mol_atom_groups.contains_key(&atom.mol_name) {
                mol_order.push(atom.mol_name.clone());
                mol_atom_groups.insert(atom.mol_name.clone(), Vec::new());
            }
            mol_atom_groups.get_mut(&atom.mol_name).unwrap().push(i);
        }

        let mut mols = Vec::new();
        let mut snap_atom_i = 0;

        for name in &mol_order {
            let indices = &mol_atom_groups[name];
            let mut atoms = Vec::new();
            let mut atom_posits = Vec::new();

            for &idx in indices {
                let a = &gro.atoms[idx];
                // GRO coords are in nm; convert to Å.
                let posit = Vec3 {
                    x: a.posit.x * 10.0,
                    y: a.posit.y * 10.0,
                    z: a.posit.z * 10.0,
                };

                atoms.push(Atom {
                    serial_number: a.serial_number,
                    posit,
                    element: a.element,
                    type_in_res_general: Some(a.atom_type.clone()),
                    hetero: true,
                    ..Default::default()
                });
                atom_posits.push(posit);
            }

            let count = atoms.len();
            let mol = MoleculeCommon {
                ident: name.clone(),
                atoms,
                atom_posits,
                ..Default::default()
            };

            mols.push(ViewerMolecule {
                mol_type: MolType::Ligand, // todo: Detect from residue name A/R.
                mol,
                range: (snap_atom_i, snap_atom_i + count),
            });

            snap_atom_i += count;
        }

        self.mol_sets.push(ViewerMolSet::new(
            Some(path.to_owned()),
            path.file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_default()
                .to_owned(),
            mols,
        ));

        if self.mol_sets.len() == 1 {
            self.mol_set_active = Some(0)
        }

        Ok(())
    }

    // todo: Removed for now. You will likely need to add something like this back.
    // todo: Or: Generate a custom peptide molecule which is properly filtered.

    // /// We filter peptide hetero atoms out of the MD workflow. Adjust snapshot indices and atom positions so they
    // /// are properly synchronized. This also handles the case of reassigning due to peptide atoms near the ligand.
    // pub fn reassign_snapshot_indices(&mut self) {
    //     // if !pep.common.selected_for_md {
    //     if self.peptides.is_empty() {
    //         return;
    //     }
    //
    //     let pep_atom_set = &self.peptide_selected;
    //
    //     let pep = &self.peptides[0];
    //
    //     println!("Re-assigning snapshot indices to match atoms excluded for MD...");
    //
    //     let pep_count = pep_atom_set.len();
    //     let lig_atom_count = self.small.len();
    //     let lipid_atom_count = self.lipids.len();
    //     let na_atom_count = self.nucleic_acids.len();
    //
    //     let pep_start_i = lig_atom_count + lipid_atom_count + na_atom_count;
    //
    //     // Rebuild each snapshot's atom_posits: [ligands as-is] + [full peptide with holes filled]
    //     for snap in &mut self.snapshots {
    //         if pep_start_i + pep_count > snap.atom_posits.len() {
    //             eprintln!(
    //                 "Error: Invalid index when reassigning snapshot posits. \
    //         Snap atom count: {}, lig count {lig_atom_count} Pep start: {pep_start_i}, Pep count: {pep_count}",
    //                 snap.atom_posits.len()
    //             );
    //             continue;
    //         }
    //
    //         // Iterator over the peptide positions that actually participated in MD
    //         let mut pept_md_posits = snap.atom_posits[pep_start_i..pep_start_i + pep_count]
    //             .iter()
    //             .cloned();
    //
    //         // Owned iterator over the peptide's MD velocities, when available.
    //         let mut pept_md_vel_iter = snap.atom_velocities.as_ref().map(|vels| {
    //             vels[pep_start_i..pep_start_i + pep_count]
    //                 .to_vec()
    //                 .into_iter()
    //         });
    //
    //         let mut new_posits = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //
    //         // Mirror the Option: only build a velocity Vec when velocities are present.
    //         let mut new_vels: Option<Vec<lin_alg::f32::Vec3>> =
    //             snap.atom_velocities.as_ref().map(|vels| {
    //                 let mut v = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //                 v.extend_from_slice(&vels[..pep_start_i]);
    //                 v
    //             });
    //
    //         // Keep ligand portion unchanged
    //         new_posits.extend_from_slice(&snap.atom_posits[..pep_start_i]);
    //
    //         // Reinsert peptide atoms in their original order
    //         for (i, atom) in pep.common.atoms.iter().enumerate() {
    //             let is_included = pep_atom_set.contains(&(0, i));
    //
    //             if is_included {
    //                 new_posits.push(
    //                     pept_md_posits
    //                         .next()
    //                         .expect("Ran out of peptide MD positions"),
    //                 );
    //
    //                 if let (Some(v), Some(it)) = (&mut new_vels, &mut pept_md_vel_iter) {
    //                     v.push(it.next().expect("Ran out of peptide MD velocities"));
    //                 }
    //             } else {
    //                 // Non-MD atom: use its original static position
    //                 new_posits.push(atom.posit.into());
    //
    //                 if let Some(ref mut v) = new_vels {
    //                     v.push(lin_alg::f32::Vec3::new_zero());
    //                 }
    //             }
    //         }
    //
    //         // Replace the snapshot's positions with the reindexed set
    //         snap.atom_posits = new_posits;
    //         snap.atom_velocities = new_vels;
    //
    //         return;
    //     }
    //
    //     println!("Done.");
    // }

    // /// Populate `custom_solvents` with one copy of each solvent template per packed copy,
    // /// ready for snapshot-driven position updates and drawing.
    // ///
    // /// Call this *after* `update_mols_for_disp` (which clears `custom_solvents`) and
    // /// *after* `build_dynamics`, in the same order the solvent species appear in
    // /// `Solvent::Custom`.
    // pub fn update_custom_solvents_for_disp(&mut self, solvents: &[(&MoleculeSmall, usize)]) {
    //     self.custom_solvents.clear();
    //     for (template, count) in solvents {
    //         for _ in 0..*count {
    //             self.custom_solvents.push(MoleculeSmall {
    //                 common: template.common.clone(),
    //                 ..Default::default()
    //             });
    //         }
    //     }
    // }

    /// Update the molecules stored here; we render these instead of the primary state molecules, if in an
    /// appropriate mode for viewing.
    pub fn add_mols_for_disp(&mut self, mols: &[(FfMolType, &MoleculeCommon, usize)]) {
        let mut snap_atom_i = 0;

        let mut mols_ = Vec::new();

        for (mol_type, m, _count) in mols {
            let len_this_mol = m.atoms.len();

            mols_.push(ViewerMolecule {
                mol_type: MolType::from(*mol_type),
                mol: (*m).clone(),
                range: (snap_atom_i, len_this_mol),
            });

            snap_atom_i += len_this_mol;
        }

        self.mol_sets
            .push(ViewerMolSet::new(None, "MD run memory".to_owned(), mols_));
    }
}

/// Draw all molecules from the loaded MD run.
pub fn draw_mols(state: &mut State, scene: &mut Scene) {
    // todo: Only if at least one lig is involved.

    // todo: Once small mools are working, add the rest.
    let mut lig_entities = Vec::new();

    let Some(set) = state.volatile.md_local.viewer.get_active_mol_set() else {
        handle_err(
            &mut state.ui,
            "Can't draw atoms from MD; no active mol set".to_string(),
        );
        return;
    };

    // MD molecules have no bonds and need atom-level rendering regardless of global mol_view.
    let prev_mol_view = state.ui.mol_view;
    state.ui.mol_view = MoleculeView::BallAndStick;

    let num_mols = set.mols.len();
    for (i_mol, mol) in set.mols.iter().enumerate() {
        match mol.mol_type {
            MolType::Peptide => {
                // todo
                // draw_peptide(state, scene);
            }
            MolType::Ligand => {
                let mol_small = MoleculeSmall {
                    common: mol.mol.clone(),
                    ..Default::default()
                };

                lig_entities.extend(draw_mol(
                    MolGenericRef::Small(&mol_small),
                    i_mol,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    num_mols,
                ));
            }
            _ => {}
        }
    }

    state.ui.mol_view = prev_mol_view;

    let lig_class = EntityClass::Ligand as u32;
    scene.entities.retain(|ent| ent.class != lig_class);
    scene.entities.extend(lig_entities);

    // draw_all_ligs(state, scene, Some(&small));

    //
    // if !state.volatile.md_local.viewer.peptides.is_empty() {
    //     draw_peptide(state, scene);
    // }
    //
    // // When drawing MD molecules, custom solvents (e.g. octanol) are rendered as ligands
    // // alongside the regular solute.  We temporarily merge them into `mols_small` so that
    // // `draw_all_ligs` handles them in one unified pass, then restore the separation.
    // let custom_solvent_count = if state.volatile.md_local.draw_md_mols {
    //     state.volatile.md_local.viewer.custom_solvents.len()
    // } else {
    //     0
    // };
    // if custom_solvent_count > 0 {
    //     // Drain into mols_small; draw_all_ligs will render all of them.
    //     let custom: Vec<MoleculeSmall> = state
    //         .volatile
    //         .md_local
    //         .viewer
    //         .custom_solvents
    //         .drain(..)
    //         .collect();
    //     state.volatile.md_local.viewer.small.extend(custom);
    // }
    // if !state.volatile.md_local.viewer.small.is_empty() {
    //     draw_all_ligs(state, scene);
    // }
    // if custom_solvent_count > 0 {
    //     // Restore: the custom solvents were appended to the end of mols_small.
    //     let split_at = state.volatile.md_local.viewer.small.len() - custom_solvent_count;
    //     state.volatile.md_local.viewer.custom_solvents = state
    //         .volatile
    //         .md_local
    //         .viewer
    //         .small
    //         .drain(split_at..)
    //         .collect();
    // }
    //
    // if !state.volatile.md_local.viewer.lipids.is_empty() {
    //     draw_all_lipids(state, scene);
    // }
    //
    // if !state.volatile.md_local.viewer.nucleic_acids.is_empty() {
    //     draw_all_nucleic_acids(state, scene);
    // }
    //
    // // Asymmetry here: We don't store a copy of water molecules in MdStateLocal,
    // // so we draw them from the snap directly. For other mol steps, we update local
    // // mol posits with posits from the snap before running this.

    if let Some(snap) = state.volatile.md_local.viewer.get_active_snap() {
        draw_water(
            scene,
            &snap.water_o_posits,
            &snap.water_h0_posits,
            &snap.water_h1_posits,
            state.ui.visibility.hide_water,
        );
    }
}
