//! For playing back MD trajectories: Generated by Molchanica, or from a file created by any
//! MD software.

use std::{io, io::ErrorKind};

use dynamics::{FfMolType, snapshot::Snapshot};
use graphics::Scene;

use crate::{
    drawing::{
        draw_mol, draw_peptide, draw_water,
        wrappers::{draw_all_ligs, draw_all_lipids, draw_all_nucleic_acids},
    },
    mol_manip::ManipMode,
    molecules::{
        MolGenericRef, MolType, common::MoleculeCommon, lipid::MoleculeLipid,
        nucleic_acid::MoleculeNucleicAcid, peptide::MoleculePeptide, small::MoleculeSmall,
    },
    state::{OperatingMode, State},
};

/// Used to map our molecule system to trajectories; the latter of which generally (always in formats
/// we've encountered and created) uses an array of positions, not corresponding to molecules. Breaking
/// these down into molecules has implications for our rendering system, i.e. neatly and consistently
/// visualizing MD output with the same visuals as our normal viewing system.
#[derive(Clone, Debug)]
pub struct ViewerMolecule {
    pub mol_type: MolType,
    /// Note: If we have multiple "copies" of a molecule, we duplicate here.
    pub mol: MoleculeCommon,
    /// Atom (start, end) index, e.g. of a snapshot/frame.
    pub range: (usize, usize),
}

#[derive(Default)]
pub struct SnapshotViewer {
    // pub struct SnapshotViewer<M: MolGeneric> {
    /// Snapshots currently active and loaded in memory; from an MD run, or loading
    /// a trajectory file.
    pub snapshots: Vec<Snapshot>,
    pub current_snapshot: Option<usize>,
    /// We maintain independent copies of these from the primary state. These are what we display
    /// after an MD run. They may be created as copies of molecules in the primary state.
    pub mols: Vec<ViewerMolecule>,
    // pub mols: Vec<M>, // todo: Evaluate if this makes more sense
    // pub custom_solvents: Vec<MoleculeSmall>,
    pub slider_posit_ui: usize,
}

impl SnapshotViewer {
    pub fn get_active_snap(&self) -> Option<&Snapshot> {
        let Some(i) = self.current_snapshot else {
            return None;
        };

        self.get_snap(i)
    }

    pub fn get_snap(&self, i: usize) -> Option<&Snapshot> {
        if i <= self.snapshots.len() {
            Some(&self.snapshots[i])
        } else {
            None
        }
    }

    /// Update each molecule's atom positions to that in the chosen snapshot.
    pub fn change_snapshot(&mut self, snap_i: usize) -> io::Result<()> {
        let snap = match self.get_snap(snap_i) {
            Some(snap) => snap,
            None => {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    "Snapshot not found when changing",
                ));
            }
        };

        let mol_start_indices = self.mols.iter().map(|m| m.range.0).collect::<Vec<_>>();
        let posits_by_mol = snap.unflatten(&mol_start_indices)?;

        let mut i_posits = 0;

        for mol in &mut self.mols {
            for (i_p, p) in mol.mol.atom_posits.iter_mut().enumerate() {
                *p = posits_by_mol[i_posits][i_p].0.into(); // Posit only; ignore velocity.

                // TODO TEMP!
                println!("Changing atom {i_p} posit to {p}");
            }

            i_posits += 1;
        }

        Ok(())
    }

    // todo: Removed for now. You will likely need to add something like this back.
    // todo: Or: Generate a custom peptide molecule which is properly filtered.

    // /// We filter peptide hetero atoms out of the MD workflow. Adjust snapshot indices and atom positions so they
    // /// are properly synchronized. This also handles the case of reassigning due to peptide atoms near the ligand.
    // pub fn reassign_snapshot_indices(&mut self) {
    //     // if !pep.common.selected_for_md {
    //     if self.peptides.is_empty() {
    //         return;
    //     }
    //
    //     let pep_atom_set = &self.peptide_selected;
    //
    //     let pep = &self.peptides[0];
    //
    //     println!("Re-assigning snapshot indices to match atoms excluded for MD...");
    //
    //     let pep_count = pep_atom_set.len();
    //     let lig_atom_count = self.small.len();
    //     let lipid_atom_count = self.lipids.len();
    //     let na_atom_count = self.nucleic_acids.len();
    //
    //     let pep_start_i = lig_atom_count + lipid_atom_count + na_atom_count;
    //
    //     // Rebuild each snapshot's atom_posits: [ligands as-is] + [full peptide with holes filled]
    //     for snap in &mut self.snapshots {
    //         if pep_start_i + pep_count > snap.atom_posits.len() {
    //             eprintln!(
    //                 "Error: Invalid index when reassigning snapshot posits. \
    //         Snap atom count: {}, lig count {lig_atom_count} Pep start: {pep_start_i}, Pep count: {pep_count}",
    //                 snap.atom_posits.len()
    //             );
    //             continue;
    //         }
    //
    //         // Iterator over the peptide positions that actually participated in MD
    //         let mut pept_md_posits = snap.atom_posits[pep_start_i..pep_start_i + pep_count]
    //             .iter()
    //             .cloned();
    //
    //         // Owned iterator over the peptide's MD velocities, when available.
    //         let mut pept_md_vel_iter = snap.atom_velocities.as_ref().map(|vels| {
    //             vels[pep_start_i..pep_start_i + pep_count]
    //                 .to_vec()
    //                 .into_iter()
    //         });
    //
    //         let mut new_posits = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //
    //         // Mirror the Option: only build a velocity Vec when velocities are present.
    //         let mut new_vels: Option<Vec<lin_alg::f32::Vec3>> =
    //             snap.atom_velocities.as_ref().map(|vels| {
    //                 let mut v = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //                 v.extend_from_slice(&vels[..pep_start_i]);
    //                 v
    //             });
    //
    //         // Keep ligand portion unchanged
    //         new_posits.extend_from_slice(&snap.atom_posits[..pep_start_i]);
    //
    //         // Reinsert peptide atoms in their original order
    //         for (i, atom) in pep.common.atoms.iter().enumerate() {
    //             let is_included = pep_atom_set.contains(&(0, i));
    //
    //             if is_included {
    //                 new_posits.push(
    //                     pept_md_posits
    //                         .next()
    //                         .expect("Ran out of peptide MD positions"),
    //                 );
    //
    //                 if let (Some(v), Some(it)) = (&mut new_vels, &mut pept_md_vel_iter) {
    //                     v.push(it.next().expect("Ran out of peptide MD velocities"));
    //                 }
    //             } else {
    //                 // Non-MD atom: use its original static position
    //                 new_posits.push(atom.posit.into());
    //
    //                 if let Some(ref mut v) = new_vels {
    //                     v.push(lin_alg::f32::Vec3::new_zero());
    //                 }
    //             }
    //         }
    //
    //         // Replace the snapshot's positions with the reindexed set
    //         snap.atom_posits = new_posits;
    //         snap.atom_velocities = new_vels;
    //
    //         return;
    //     }
    //
    //     println!("Done.");
    // }

    // /// Populate `custom_solvents` with one copy of each solvent template per packed copy,
    // /// ready for snapshot-driven position updates and drawing.
    // ///
    // /// Call this *after* `update_mols_for_disp` (which clears `custom_solvents`) and
    // /// *after* `build_dynamics`, in the same order the solvent species appear in
    // /// `Solvent::Custom`.
    // pub fn update_custom_solvents_for_disp(&mut self, solvents: &[(&MoleculeSmall, usize)]) {
    //     self.custom_solvents.clear();
    //     for (template, count) in solvents {
    //         for _ in 0..*count {
    //             self.custom_solvents.push(MoleculeSmall {
    //                 common: template.common.clone(),
    //                 ..Default::default()
    //             });
    //         }
    //     }
    // }

    // /// Update the molecules stored here; we render these instead of the primary state molecules, if in an
    // /// appropriate mode for viewing.
    // pub fn update_mols_for_disp(&mut self, mols: &[(FfMolType, &MoleculeCommon, usize)]) {
    //     self.mols.clear();
    //
    //     // self.peptides.clear();
    //     // self.small.clear();
    //     // self.lipids.clear();
    //     // self.nucleic_acids.clear();
    //     // self.custom_solvents.clear();
    //
    //     for (ff_mol_type, mol, count) in mols {
    //         // todo: Pass in the full mols so we are not reproducing a copy?
    //         match ff_mol_type {
    //             FfMolType::Peptide => {
    //                 for _ in 0..*count {
    //                     self.peptides.push(MoleculePeptide {
    //                         common: (*mol).clone(),
    //                         ..Default::default()
    //                     });
    //                 }
    //             }
    //             FfMolType::SmallOrganic => {
    //                 for _ in 0..*count {
    //                     self.small.push(MoleculeSmall {
    //                         common: (*mol).clone(),
    //                         ..Default::default()
    //                     });
    //                 }
    //             }
    //             FfMolType::Dna | FfMolType::Rna => {
    //                 for _ in 0..*count {
    //                     self.nucleic_acids.push(MoleculeNucleicAcid {
    //                         common: (*mol).clone(),
    //                         ..Default::default()
    //                     });
    //                 }
    //             }
    //             FfMolType::Lipid => {
    //                 for _ in 0..*count {
    //                     self.lipids.push(MoleculeLipid {
    //                         common: (*mol).clone(),
    //                         ..Default::default()
    //                     });
    //                 }
    //             }
    //             _ => eprintln!("Invalid Mol type for MD"),
    //         }
    //     }
    // }
}

/// Draw all molecules from the loaded MD run.
pub fn draw_mols(state: &mut State, scene: &mut Scene) {
    // todo: Only if at least one lig is involved.

    // todo: Once small mools are working, add the rest.
    // let mut small = Vec::new();

    for mol in &state.volatile.md_local.viewer.mols {
        match mol.mol_type {
            MolType::Peptide => {
                // todo
                // draw_peptide(state, scene);
            }
            MolType::Ligand => {
                let mol_small = MoleculeSmall {
                    common: mol.mol.clone(),
                    ..Default::default()
                };
                // small.push(mol_small);
                // todo: QC this whole fn.

                println!("Drawing mol at range: {:?}", mol.range); // todo temp

                draw_mol(
                    MolGenericRef::Small(&mol_small),
                    0,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    0,
                );
            }
            _ => {}
        }
    }

    // draw_all_ligs(state, scene, Some(&small));

    //
    // if !state.volatile.md_local.viewer.peptides.is_empty() {
    //     draw_peptide(state, scene);
    // }
    //
    // // When drawing MD molecules, custom solvents (e.g. octanol) are rendered as ligands
    // // alongside the regular solute.  We temporarily merge them into `mols_small` so that
    // // `draw_all_ligs` handles them in one unified pass, then restore the separation.
    // let custom_solvent_count = if state.volatile.md_local.draw_md_mols {
    //     state.volatile.md_local.viewer.custom_solvents.len()
    // } else {
    //     0
    // };
    // if custom_solvent_count > 0 {
    //     // Drain into mols_small; draw_all_ligs will render all of them.
    //     let custom: Vec<MoleculeSmall> = state
    //         .volatile
    //         .md_local
    //         .viewer
    //         .custom_solvents
    //         .drain(..)
    //         .collect();
    //     state.volatile.md_local.viewer.small.extend(custom);
    // }
    // if !state.volatile.md_local.viewer.small.is_empty() {
    //     draw_all_ligs(state, scene);
    // }
    // if custom_solvent_count > 0 {
    //     // Restore: the custom solvents were appended to the end of mols_small.
    //     let split_at = state.volatile.md_local.viewer.small.len() - custom_solvent_count;
    //     state.volatile.md_local.viewer.custom_solvents = state
    //         .volatile
    //         .md_local
    //         .viewer
    //         .small
    //         .drain(split_at..)
    //         .collect();
    // }
    //
    // if !state.volatile.md_local.viewer.lipids.is_empty() {
    //     draw_all_lipids(state, scene);
    // }
    //
    // if !state.volatile.md_local.viewer.nucleic_acids.is_empty() {
    //     draw_all_nucleic_acids(state, scene);
    // }
    //
    // // Asymmetry here: We don't store a copy of water molecules in MdStateLocal,
    // // so we draw them from the snap directly. For other mol steps, we update local
    // // mol posits with posits from the snap before running this.

    if let Some(snap) = state.volatile.md_local.viewer.get_active_snap() {
        draw_water(
            scene,
            &snap.water_o_posits,
            &snap.water_h0_posits,
            &snap.water_h1_posits,
            state.ui.visibility.hide_water,
        );
    }
}
