//! For playing back MD trajectories: Generated by Molchanica, or from a file created by any
//! MD software.

use bio_files::{AtomGeneric, bond_inference, gromacs::gro::Gro};
use dynamics::{FfMolType, snapshot::Snapshot};
use graphics::{EngineUpdates, EntityUpdate, Scene};
use lin_alg::f64::Vec3;
use na_seq::Element;
use std::{
    collections::HashMap,
    io,
    io::ErrorKind,
    path::{Path, PathBuf},
};

use crate::{
    drawing::{MoleculeView, blend_color, color_viridis, draw_mol, draw_water},
    mol_manip::ManipMode,
    molecules::{
        Atom, Bond, MolGenericRef, MolType, common::MoleculeCommon, lipid::MoleculeLipid,
        nucleic_acid::MoleculeNucleicAcid, small::MoleculeSmall,
    },
    prefs::{OpenHistory, OpenType},
    state::{OperatingMode, State},
    util::handle_err,
};

/// Used to map our molecule system to trajectories; the latter of which generally (always in formats
/// we've encountered and created) uses an array of positions, not corresponding to molecules. Breaking
/// these down into molecules has implications for our rendering system, i.e. neatly and consistently
/// visualizing MD output with the same visuals as our normal viewing system.
#[derive(Clone, Debug)]
pub struct ViewerMolecule {
    pub mol_type: MolType,
    /// Note: If we have multiple "copies" of a molecule, we duplicate here.
    pub mol: MoleculeCommon,
    /// Atom (start, end) index, e.g. of a snapshot/frame.
    pub range: (usize, usize),
}

/// Groups molecules by type. For example, all instances of a given molecule identifier
/// will be grouped together. This allows us to color each molecule type differently,
/// and hide ones as required.
/// ((start, end) ranges, visible).
#[derive(Clone, Debug)]
pub struct ViewerGroup {
    pub ident: String,
    /// Indexes of `ViewerMolSet::mols`.
    pub ranges: Vec<(usize, usize)>,
    pub visible: bool,
}

/// E.g. from a .gro file or similar.
#[derive(Debug)]
pub struct ViewerMolSet {
    pub path: Option<PathBuf>,
    pub name: String,
    pub mols: Vec<ViewerMolecule>,
    /// Derivative of mols. Used to compare to atom counts in trajectories.
    pub atom_count: usize,
    /// Derived from all molecule ranges in the set
    pub range_covered: (usize, usize),
    /// A range overlap is probably a fault of some sort in the ranges here.
    pub range_overlaps: bool,
    pub groups: Vec<ViewerGroup>,
}

#[derive(Clone, Debug)]
pub struct ViewerGroupDisplay {
    pub group_i: usize,
    pub ident: String,
    pub mol_count: usize,
    pub atom_count: usize,
    pub range_covered: (usize, usize),
    pub visible: bool,
}

impl ViewerMolSet {
    /// This constructor computes the derivative values.
    pub fn new(path: Option<PathBuf>, name: String, mols: Vec<ViewerMolecule>) -> Self {
        let mut result = Self {
            path,
            name,
            mols,
            atom_count: 0,
            range_covered: (0, 0),
            range_overlaps: false,
            groups: Vec::new(),
        };

        result.update_derivative_vals();

        result
    }

    pub fn update_derivative_vals(&mut self) {
        self.atom_count = self.mols.iter().map(|m| m.mol.atoms.len()).sum();

        self.range_covered = if self.mols.is_empty() {
            (0, 0)
        } else {
            let start = self.mols.iter().map(|m| m.range.0).min().unwrap();
            let end = self.mols.iter().map(|m| m.range.1).max().unwrap();
            (start, end)
        };

        let mut sorted_ranges = self.mols.iter().map(|m| m.range).collect::<Vec<_>>();
        sorted_ranges.sort_by_key(|r| r.0);

        let mut range_overlaps = false;
        for pair in sorted_ranges.windows(2) {
            let a = pair[0];
            let b = pair[1];

            if b.0 < a.1 {
                range_overlaps = true;
                break;
            }
        }

        self.range_overlaps = range_overlaps;

        let visible_by_ident: HashMap<String, bool> = self
            .groups
            .iter()
            .map(|group| (group.ident.clone(), group.visible))
            .collect();

        let mut mols_sorted = self.mols.iter().collect::<Vec<_>>();
        mols_sorted.sort_by_key(|mol| mol.range.0);

        let mut group_i_by_ident: HashMap<String, usize> = HashMap::new();
        let mut groups: Vec<ViewerGroup> = Vec::new();

        for mol in mols_sorted {
            let ident = mol.mol.ident.clone();

            if let Some(group_i) = group_i_by_ident.get(&ident) {
                groups[*group_i].ranges.push(mol.range);
            } else {
                let group_i = groups.len();
                group_i_by_ident.insert(ident.clone(), group_i);
                groups.push(ViewerGroup {
                    ident: ident.clone(),
                    ranges: vec![mol.range],
                    visible: *visible_by_ident.get(&ident).unwrap_or(&true),
                });
            }
        }

        self.groups = groups;
    }

    pub fn groups_display(&self) -> Vec<ViewerGroupDisplay> {
        let mol_by_range: HashMap<(usize, usize), &ViewerMolecule> =
            self.mols.iter().map(|mol| (mol.range, mol)).collect();

        let mut result = Vec::new();

        for (group_i, group) in self.groups.iter().enumerate() {
            let mut atom_count = 0;
            let mut range_start = usize::MAX;
            let mut range_end = 0;

            for range in &group.ranges {
                let Some(mol) = mol_by_range.get(range) else {
                    continue;
                };

                atom_count += mol.mol.atoms.len();
                range_start = range_start.min(range.0);
                range_end = range_end.max(range.1);
            }

            if range_start == usize::MAX {
                range_start = 0;
            }

            result.push(ViewerGroupDisplay {
                group_i,
                ident: group.ident.clone(),
                mol_count: group.ranges.len(),
                atom_count,
                range_covered: (range_start, range_end),
                visible: group.visible,
            });
        }

        result.sort_by_key(|group| group.range_covered.0);

        result
    }
}

#[derive(Default)]
pub struct SnapshotViewer {
    // pub struct SnapshotViewer<M: MolGeneric> {
    /// Snapshots currently active and loaded in memory; from an MD run, or loading
    /// a trajectory file.
    pub snapshots: Vec<Snapshot>,
    pub current_snapshot: Option<usize>,
    /// We maintain independent copies of these from the primary state. These are what we display
    /// after an MD run. They may be created as copies of molecules in the primary state, or loaded
    /// from an MD file like .gro.
    pub mol_sets: Vec<ViewerMolSet>,
    pub mol_set_active: Option<usize>,
    // pub mols: Vec<M>, // todo: Evaluate if this makes more sense
    // pub custom_solvents: Vec<MoleculeSmall>,
    pub slider_posit_ui: usize,
}

impl SnapshotViewer {
    pub fn get_active_snap(&self) -> Option<&Snapshot> {
        let Some(i) = self.current_snapshot else {
            return None;
        };

        self.get_snap(i)
    }

    pub fn get_snap(&self, i: usize) -> Option<&Snapshot> {
        if i < self.snapshots.len() {
            Some(&self.snapshots[i])
        } else {
            None
        }
    }

    pub fn get_snap_mut(&mut self, i: usize) -> Option<&mut Snapshot> {
        if i < self.snapshots.len() {
            Some(&mut self.snapshots[i])
        } else {
            None
        }
    }

    pub fn get_active_mol_set(&self) -> Option<&ViewerMolSet> {
        let i = self.mol_set_active?;

        if i < self.mol_sets.len() {
            Some(&self.mol_sets[i])
        } else {
            None
        }
    }

    pub fn get_active_mol_set_mut(&mut self) -> Option<&mut ViewerMolSet> {
        let i = self.mol_set_active?;

        if i < self.mol_sets.len() {
            Some(&mut self.mol_sets[i])
        } else {
            None
        }
    }

    /// Update each molecule's atom positions to that in the chosen snapshot.
    pub fn change_snapshot(&mut self, snap_i: usize) -> io::Result<()> {
        // Determine whether water positions come inline from the snapshot (in-memory dynamics)
        // or need to be reconstructed from Water-typed mol entries (file-based / GRO path).
        let has_inline_water = self
            .get_snap(snap_i)
            .map_or(false, |s| !s.water_o_posits.is_empty());

        // Build mol_start_indices for unflatten.  For in-memory dynamics we exclude Water
        // mols because their positions live in the snapshot's water_* arrays, not atom_posits.
        let mol_start_indices = {
            let Some(set) = self.get_active_mol_set() else {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    "No active mol set when changing snap.",
                ));
            };

            set.mols
                .iter()
                .filter(|m| !has_inline_water || m.mol_type != MolType::Water)
                .map(|m| m.range.0)
                .collect::<Vec<_>>()
        };

        // GRO / file-based path: reconstruct water positions from Water mol entries and
        // push them into the snapshot so subsequent steps can use them.
        let reconstructed_water: Vec<(Vec3, Vec3, Vec3)> = if !has_inline_water {
            if let Some(set) = self.get_active_mol_set() {
                set.mols
                    .iter()
                    .filter(|mol| mol.mol_type == MolType::Water)
                    .filter_map(|mol| {
                        let mut ow = None;
                        let mut hw1 = None;
                        let mut hw2 = None;

                        for (i, atom) in mol.mol.atoms.iter().enumerate() {
                            match atom.type_in_res_general.as_deref() {
                                Some("OW") => ow = Some(mol.mol.atom_posits[i]),
                                Some("HW1") => hw1 = Some(mol.mol.atom_posits[i]),
                                Some("HW2") => hw2 = Some(mol.mol.atom_posits[i]),
                                _ => {}
                            }
                        }

                        match (ow, hw1, hw2) {
                            (Some(o), Some(h0), Some(h1)) => Some((o, h0, h1)),
                            _ => {
                                eprintln!(
                                    "Water mol missing atom(s): OW={}, HW1={}, HW2={}",
                                    ow.is_some(),
                                    hw1.is_some(),
                                    hw2.is_some()
                                );
                                None
                            }
                        }
                    })
                    .collect()
            } else {
                Vec::new()
            }
        } else {
            Vec::new()
        };

        if !reconstructed_water.is_empty() {
            if snap_i < self.snapshots.len() {
                let snap = &mut self.snapshots[snap_i];
                for (o, h0, h1) in reconstructed_water {
                    snap.water_o_posits.push(o.into());
                    snap.water_h0_posits.push(h0.into());
                    snap.water_h1_posits.push(h1.into());
                }
            }
        }

        // Collect inline water positions before taking the mutable borrow.
        // Each element: (O, H0, H1) in f32 coords (snapshot units, Å).
        let inline_water: Vec<(lin_alg::f32::Vec3, lin_alg::f32::Vec3, lin_alg::f32::Vec3)> =
            if has_inline_water {
                if let Some(snap) = self.get_snap(snap_i) {
                    snap.water_o_posits
                        .iter()
                        .zip(snap.water_h0_posits.iter())
                        .zip(snap.water_h1_posits.iter())
                        .map(|((o, h0), h1)| (*o, *h0, *h1))
                        .collect()
                } else {
                    Vec::new()
                }
            } else {
                Vec::new()
            };

        let posits_by_mol = {
            let Some(snap) = self.get_snap(snap_i) else {
                return Err(io::Error::new(
                    ErrorKind::NotFound,
                    "Snapshot not found when changing",
                ));
            };

            snap.unflatten(&mol_start_indices)?
        };

        let Some(mols) = self.get_active_mol_set_mut() else {
            return Err(io::Error::new(
                ErrorKind::NotFound,
                "No active mol set when changing snap.",
            ));
        };

        let pbm_len = posits_by_mol.len();
        let mut non_water_i = 0;
        let mut water_i = 0;

        for mol in mols.mols.iter_mut() {
            if mol.mol_type == MolType::Water && has_inline_water {
                // Update from the snapshot's inline water arrays.
                if let Some((o, h0, h1)) = inline_water.get(water_i) {
                    for (i, p) in mol.mol.atom_posits.iter_mut().enumerate() {
                        let name = mol
                            .mol
                            .atoms
                            .get(i)
                            .and_then(|a| a.type_in_res_general.as_deref());
                        match name {
                            Some("OW") => {
                                *p = Vec3 {
                                    x: o.x as f64,
                                    y: o.y as f64,
                                    z: o.z as f64,
                                }
                            }
                            Some("HW1") => {
                                *p = Vec3 {
                                    x: h0.x as f64,
                                    y: h0.y as f64,
                                    z: h0.z as f64,
                                }
                            }
                            Some("HW2") => {
                                *p = Vec3 {
                                    x: h1.x as f64,
                                    y: h1.y as f64,
                                    z: h1.z as f64,
                                }
                            }
                            _ => {}
                        }
                    }
                }
                water_i += 1;
            } else {
                // Update from unflatten (handles all mols for file-based, non-water for in-memory).
                if non_water_i < pbm_len {
                    for (i_p, p) in mol.mol.atom_posits.iter_mut().enumerate() {
                        if non_water_i >= pbm_len {
                            eprintln!(
                                "Error: posit {non_water_i} out of bounds for posits-by-mol len {pbm_len}"
                            );
                        } else {
                            if i_p >= posits_by_mol[non_water_i].len() {
                                eprintln!(
                                    "Error: posit {i_p} out of bounds for posits-by-mol for this non-water index len {}",
                                    posits_by_mol[non_water_i].len()
                                );
                            } else {
                                *p = posits_by_mol[non_water_i][i_p].0.into();
                            }
                        }
                    }
                } else {
                    eprintln!(
                        "Error: Posits by mol in viewer out of bounds. i: {non_water_i} Posits by mol len: {pbm_len}"
                    );
                }
                non_water_i += 1;
            }
        }

        Ok(())
    }

    /// Opens a GROMACS gro file. We currently are adding it only for the purposes of MD playback.
    /// This replaces all molecules in the viewer.
    /// todo: Support more generally as a molecule format A/R, and possibly move this if so.
    pub fn load_gro(&mut self, path: &Path) -> io::Result<()> {
        let gro = Gro::load(path)?;

        // Group atoms by (mol_id, mol_name), preserving first-seen order.
        // mol_id (the GRO resid) is unique per molecule instance, so e.g. each SOL water
        // gets its own entry rather than all being merged into one giant "SOL".
        let mut mol_order: Vec<(u32, String)> = Vec::new();
        let mut mol_atom_groups: HashMap<(u32, String), Vec<usize>> = HashMap::new();

        for (i, atom) in gro.atoms.iter().enumerate() {
            let key = (atom.mol_id, atom.mol_name.clone());
            if !mol_atom_groups.contains_key(&key) {
                mol_order.push(key.clone());
                mol_atom_groups.insert(key.clone(), Vec::new());
            }
            mol_atom_groups.get_mut(&key).unwrap().push(i);
        }

        let mut mols = Vec::new();
        let mut snap_atom_i = 0;

        for (mol_id, mol_name) in &mol_order {
            let indices = &mol_atom_groups[&(*mol_id, mol_name.clone())];
            let mut atoms = Vec::new();
            let mut atom_posits = Vec::new();

            for &idx in indices {
                let a = &gro.atoms[idx];
                // GRO coords are in nm; convert to Å.
                let posit = Vec3 {
                    x: a.posit.x * 10.0,
                    y: a.posit.y * 10.0,
                    z: a.posit.z * 10.0,
                };

                atoms.push(Atom {
                    serial_number: a.serial_number,
                    posit,
                    element: a.element,
                    type_in_res_general: Some(a.atom_type.clone()),
                    hetero: true,
                    ..Default::default()
                });
                atom_posits.push(posit);
            }

            // Infer covalent bonds from atom distances.
            let atom_generics: Vec<AtomGeneric> = atoms
                .iter()
                .zip(atom_posits.iter())
                .map(|(a, posit)| AtomGeneric {
                    serial_number: a.serial_number,
                    posit: *posit,
                    element: a.element,
                    ..Default::default()
                })
                .collect();

            let bond_generics = bond_inference::create_bonds(&atom_generics);
            let bonds: Vec<Bond> = bond_generics
                .iter()
                .filter_map(|bg| Bond::from_generic(bg, &atoms).ok())
                .collect();

            let count = atoms.len();
            let mut mol = MoleculeCommon {
                ident: mol_name.clone(),
                atoms,
                bonds,
                atom_posits,
                ..Default::default()
            };
            mol.build_adjacency_list();

            // todo: Determine, using type in res or similar, if it's a NA or lipid
            let mol_type = if is_water(&mol) {
                MolType::Water
            } else {
                MolType::Ligand
            };

            mols.push(ViewerMolecule {
                mol_type,
                mol,
                range: (snap_atom_i, snap_atom_i + count),
            });

            snap_atom_i += count;
        }

        self.mol_sets.push(ViewerMolSet::new(
            Some(path.to_owned()),
            path.file_name()
                .and_then(|s| s.to_str())
                .unwrap_or_default()
                .to_owned(),
            mols,
        ));

        if self.mol_sets.len() == 1 {
            self.mol_set_active = Some(0)
        }

        Ok(())
    }

    // todo: Removed for now. You will likely need to add something like this back.
    // todo: Or: Generate a custom peptide molecule which is properly filtered.

    // /// We filter peptide hetero atoms out of the MD workflow. Adjust snapshot indices and atom positions so they
    // /// are properly synchronized. This also handles the case of reassigning due to peptide atoms near the ligand.
    // pub fn reassign_snapshot_indices(&mut self) {
    //     // if !pep.common.selected_for_md {
    //     if self.peptides.is_empty() {
    //         return;
    //     }
    //
    //     let pep_atom_set = &self.peptide_selected;
    //
    //     let pep = &self.peptides[0];
    //
    //     println!("Re-assigning snapshot indices to match atoms excluded for MD...");
    //
    //     let pep_count = pep_atom_set.len();
    //     let lig_atom_count = self.small.len();
    //     let lipid_atom_count = self.lipids.len();
    //     let na_atom_count = self.nucleic_acids.len();
    //
    //     let pep_start_i = lig_atom_count + lipid_atom_count + na_atom_count;
    //
    //     // Rebuild each snapshot's atom_posits: [ligands as-is] + [full peptide with holes filled]
    //     for snap in &mut self.snapshots {
    //         if pep_start_i + pep_count > snap.atom_posits.len() {
    //             eprintln!(
    //                 "Error: Invalid index when reassigning snapshot posits. \
    //         Snap atom count: {}, lig count {lig_atom_count} Pep start: {pep_start_i}, Pep count: {pep_count}",
    //                 snap.atom_posits.len()
    //             );
    //             continue;
    //         }
    //
    //         // Iterator over the peptide positions that actually participated in MD
    //         let mut pept_md_posits = snap.atom_posits[pep_start_i..pep_start_i + pep_count]
    //             .iter()
    //             .cloned();
    //
    //         // Owned iterator over the peptide's MD velocities, when available.
    //         let mut pept_md_vel_iter = snap.atom_velocities.as_ref().map(|vels| {
    //             vels[pep_start_i..pep_start_i + pep_count]
    //                 .to_vec()
    //                 .into_iter()
    //         });
    //
    //         let mut new_posits = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //
    //         // Mirror the Option: only build a velocity Vec when velocities are present.
    //         let mut new_vels: Option<Vec<lin_alg::f32::Vec3>> =
    //             snap.atom_velocities.as_ref().map(|vels| {
    //                 let mut v = Vec::with_capacity(pep_start_i + pep.common.atoms.len());
    //                 v.extend_from_slice(&vels[..pep_start_i]);
    //                 v
    //             });
    //
    //         // Keep ligand portion unchanged
    //         new_posits.extend_from_slice(&snap.atom_posits[..pep_start_i]);
    //
    //         // Reinsert peptide atoms in their original order
    //         for (i, atom) in pep.common.atoms.iter().enumerate() {
    //             let is_included = pep_atom_set.contains(&(0, i));
    //
    //             if is_included {
    //                 new_posits.push(
    //                     pept_md_posits
    //                         .next()
    //                         .expect("Ran out of peptide MD positions"),
    //                 );
    //
    //                 if let (Some(v), Some(it)) = (&mut new_vels, &mut pept_md_vel_iter) {
    //                     v.push(it.next().expect("Ran out of peptide MD velocities"));
    //                 }
    //             } else {
    //                 // Non-MD atom: use its original static position
    //                 new_posits.push(atom.posit.into());
    //
    //                 if let Some(ref mut v) = new_vels {
    //                     v.push(lin_alg::f32::Vec3::new_zero());
    //                 }
    //             }
    //         }
    //
    //         // Replace the snapshot's positions with the reindexed set
    //         snap.atom_posits = new_posits;
    //         snap.atom_velocities = new_vels;
    //
    //         return;
    //     }
    //
    //     println!("Done.");
    // }

    // /// Populate `custom_solvents` with one copy of each solvent template per packed copy,
    // /// ready for snapshot-driven position updates and drawing.
    // ///
    // /// Call this *after* `update_mols_for_disp` (which clears `custom_solvents`) and
    // /// *after* `build_dynamics`, in the same order the solvent species appear in
    // /// `Solvent::Custom`.
    // pub fn update_custom_solvents_for_disp(&mut self, solvents: &[(&MoleculeSmall, usize)]) {
    //     self.custom_solvents.clear();
    //     for (template, count) in solvents {
    //         for _ in 0..*count {
    //             self.custom_solvents.push(MoleculeSmall {
    //                 common: template.common.clone(),
    //                 ..Default::default()
    //             });
    //         }
    //     }
    // }

    /// Update the molecules stored here; we render these instead of the primary state molecules, if in an
    /// appropriate mode for viewing.
    pub fn add_mol_set(&mut self, mols: &[(FfMolType, &MoleculeCommon, usize)], num_water: usize) {
        let mut snap_atom_i = 0;

        let mut mols_ = Vec::new();

        for (mol_type, m, _count) in mols {
            let len_this_mol = m.atoms.len();

            mols_.push(ViewerMolecule {
                mol_type: MolType::from(*mol_type),
                mol: (*m).clone(),
                range: (snap_atom_i, snap_atom_i + len_this_mol),
            });

            snap_atom_i += len_this_mol;
        }

        // Add one ViewerMolecule per water molecule.  Positions start at zero; change_snapshot
        // will overwrite them from the snapshot's water_o/h0/h1_posits arrays.
        // We use `type_in_res_general` names matching the GRO convention so the same
        // atom-name matching logic in change_snapshot works for both paths.
        for i in 0..num_water {
            let zero = Vec3::default();
            let atoms = vec![
                Atom {
                    serial_number: (snap_atom_i + i * 3) as u32,
                    posit: zero,
                    type_in_res_general: Some("OW".to_owned()),
                    hetero: true,
                    element: Element::Oxygen,
                    ..Default::default()
                },
                Atom {
                    serial_number: (snap_atom_i + i * 3 + 1) as u32,
                    posit: zero,
                    type_in_res_general: Some("HW1".to_owned()),
                    hetero: true,
                    element: Element::Hydrogen,
                    ..Default::default()
                },
                Atom {
                    serial_number: (snap_atom_i + i * 3 + 2) as u32,
                    posit: zero,
                    type_in_res_general: Some("HW2".to_owned()),
                    hetero: true,
                    element: Element::Hydrogen,
                    ..Default::default()
                },
            ];
            let atom_posits = vec![zero; 3];

            // Range continues past the non-water atoms for correct display and overlap
            // detection.  change_snapshot uses a counter (not range.0) to index the water
            // arrays, so this is purely for display / metadata purposes.
            let water_start = snap_atom_i + i * 3;
            mols_.push(ViewerMolecule {
                mol_type: MolType::Water,
                mol: MoleculeCommon {
                    ident: "SOL".to_owned(),
                    atoms,
                    atom_posits,
                    ..Default::default()
                },
                range: (water_start, water_start + 3),
            });
        }

        let set_i = self.mol_sets.len();
        self.mol_sets
            .push(ViewerMolSet::new(None, "MD run memory".to_owned(), mols_));

        if self.mol_set_active.is_none() {
            self.mol_set_active = Some(set_i);
        }
    }

    /// A metric to determine if we're ready to view MD atoms. Checks that there's an active snapshot,
    /// an active mol set, and that their atom counts match.
    pub fn mols_and_traj_synced(&self) -> bool {
        let Some(set) = &self.get_active_mol_set() else {
            return false;
        };

        if self.snapshots.is_empty() {
            return false;
        }

        let snap = &self.snapshots[0];
        let n = snap.atom_posits.len();

        // File-based snapshots store all atoms (including water) in atom_posits.
        if n == set.atom_count {
            return true;
        }

        // In-memory dynamics snapshots store only non-water atoms in atom_posits.
        let non_water_count: usize = set
            .mols
            .iter()
            .filter(|m| m.mol_type != MolType::Water)
            .map(|m| m.mol.atoms.len())
            .sum();

        n == non_water_count
    }

    pub fn close_mol_set(&mut self, history: &mut Vec<OpenHistory>, i: usize) {
        if i >= self.mol_sets.len() {
            eprintln!("Error: Attempting to close mol set not opened");
            return;
        }

        self.mol_set_active = match self.mol_set_active {
            Some(active) if active == i => None,
            Some(active) if active > i => Some(active - 1),
            other => other,
        };

        let set = &self.mol_sets[i];
        for history in history {
            if let Some(p) = &set.path
                && OpenType::MdMols == history.type_
                && &history.path == p
            {
                history.last_session = false;
            }
        }

        self.mol_sets.remove(i);
    }
}

/// Draw all molecules from the loaded MD run.
pub fn draw_mols(state: &mut State, scene: &mut Scene, updates: &mut EngineUpdates) {
    const BLEND_AMT_MD_GROUP: f32 = 0.35;

    let mut ents = Vec::new();

    let Some(set) = state.volatile.md_local.viewer.get_active_mol_set() else {
        handle_err(
            &mut state.ui,
            "Can't draw atoms from MD; no active mol set".to_string(),
        );
        return;
    };

    // MD molecules have no bonds and need atom-level rendering regardless of global mol_view.
    let prev_mol_view = state.ui.mol_view;
    state.ui.mol_view = MoleculeView::BallAndStick;

    let num_mols = set.mols.len();
    let num_groups = set.groups.len();
    let range_to_group: HashMap<(usize, usize), usize> = set
        .groups
        .iter()
        .enumerate()
        .flat_map(|(group_i, group)| group.ranges.iter().map(move |range| (*range, group_i)))
        .collect();

    let mut water_o_posits = Vec::new();
    let mut water_h0_posits = Vec::new();
    let mut water_h1_posits = Vec::new();

    for (i_mol, mol) in set.mols.iter().enumerate() {
        let Some(group_i) = range_to_group.get(&mol.range).copied() else {
            continue;
        };
        let Some(group) = set.groups.get(group_i) else {
            continue;
        };

        if !group.visible {
            continue;
        }

        let group_color = color_viridis(group_i, 0, num_groups);

        match mol.mol_type {
            MolType::Peptide => {
                let mol_ = MoleculeSmall {
                    common: mol.mol.clone(),
                    ..Default::default()
                };
                let mut ents_this = draw_mol(
                    MolGenericRef::Small(&mol_),
                    i_mol,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    num_mols,
                );
                for ent in &mut ents_this {
                    ent.color = blend_color(ent.color, group_color, BLEND_AMT_MD_GROUP);
                }
                ents.extend(ents_this);
            }
            MolType::Ligand => {
                let mol_ = MoleculeSmall {
                    common: mol.mol.clone(),
                    ..Default::default()
                };

                let mut ents_this = draw_mol(
                    MolGenericRef::Small(&mol_),
                    i_mol,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    num_mols,
                );
                for ent in &mut ents_this {
                    ent.color = blend_color(ent.color, group_color, BLEND_AMT_MD_GROUP);
                }
                ents.extend(ents_this);
            }
            MolType::NucleicAcid => {
                let mol_ = MoleculeNucleicAcid {
                    common: mol.mol.clone(),
                    ..Default::default()
                };

                let mut ents_this = draw_mol(
                    MolGenericRef::NucleicAcid(&mol_),
                    i_mol,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    num_mols,
                );
                for ent in &mut ents_this {
                    ent.color = blend_color(ent.color, group_color, BLEND_AMT_MD_GROUP);
                }
                ents.extend(ents_this);
            }
            MolType::Lipid => {
                let mol_ = MoleculeLipid {
                    common: mol.mol.clone(),
                    ..Default::default()
                };

                let mut ents_this = draw_mol(
                    MolGenericRef::Lipid(&mol_),
                    i_mol,
                    &state.ui,
                    &None,
                    ManipMode::None,
                    OperatingMode::Primary,
                    num_mols,
                );
                for ent in &mut ents_this {
                    ent.color = blend_color(ent.color, group_color, BLEND_AMT_MD_GROUP);
                }
                ents.extend(ents_this);
            }
            MolType::Water => {
                let mut o = None;
                let mut h0 = None;
                let mut h1 = None;

                for (atom_i, atom) in mol.mol.atoms.iter().enumerate() {
                    let posit = mol.mol.atom_posits[atom_i];
                    match atom.type_in_res_general.as_deref() {
                        Some("OW") => o = Some(posit.into()),
                        Some("HW1") => h0 = Some(posit.into()),
                        Some("HW2") => h1 = Some(posit.into()),
                        _ => {}
                    }
                }

                if let (Some(o), Some(h0), Some(h1)) = (o, h0, h1) {
                    water_o_posits.push(o);
                    water_h0_posits.push(h0);
                    water_h1_posits.push(h1);
                }
            }
            _ => {}
        }
    }

    state.ui.mol_view = prev_mol_view;

    scene.entities.clear();
    scene.entities.extend(ents);
    updates.entities = EntityUpdate::All;

    if !water_o_posits.is_empty() {
        draw_water(
            scene,
            &water_o_posits,
            &water_h0_posits,
            &water_h1_posits,
            state.ui.visibility.hide_water,
        );
    }
}

pub fn is_water(mol: &MoleculeCommon) -> bool {
    if mol.ident.to_lowercase().contains("sol") {
        return true;
    }

    let mut h_count = 0;
    let mut o_count = 0;
    let mut other_count = 0;

    for atom in &mol.atoms {
        if atom.type_in_res_general == Some("MW".to_owned()) {
            return true;
        }

        match atom.element {
            Element::Hydrogen => h_count += 1,
            Element::Oxygen => o_count += 1,
            _ => other_count += 1,
        }
    }

    // todo: Make sure the M/EP site isn't spoiling this.
    if h_count == 2 && o_count == 1 && other_count == 0 {
        return true;
    }

    false
}
